# Generated by Django 4.2.7 on 2024-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('chat_id', models.CharField(max_length=100)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_message', models.TextField()),
            ],
        ),
    ]
